### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by ngodi**

### CODE REVIEW

**Comment by adriaanbd** [comment]
# Code Review No. 1

I enjoyed reading some of your framework ideas, i.e. full vs partial width, column sizes, text-align left and right, among others.

As far as the requirements for this project go, I think we could do a better job in point 3:
> Think about the major elements that are required of a framework. This includes a CSS reset, a fixed number of grids separated by “gutters”, a way to make new rows, and default values for the font properties of elements.

Therefore, mandatory changes:

* Did you include a way to make gutters in your grid? 

* Have you thought about common font properties that could be added to your framework?

Optional:

* Have you evaluated refactoring your CSS to avoid repetition? For example, lines [112-141](https://github.com/ngodi/css-grid-framework/blob/1fed7371e7094caffeac283b60d9bb5829ab2e61/style.css#L112-L141) is a good place to look at. If you're repeating the same things in all of those IDs, perhaps it'd be of benefit to include it in your framework?

* I've also noticed the constant use of padding and border radius, among others Have you considered making a padding or border radius class with different sizes?

**Comment by adriaanbd** [comment]
# Code Review No. 2 

Good job on abstracting away some of that repetition. Almost there!

1. How would you add or control the spacing between `row` classes, i.e. between line [35](https://github.com/ngodi/css-grid-framework/blob/023eaa2e9b1b7aff82b780b2cd5917491578ae2d/index.html#L35) and 456. Would it be useful to have a padding or margin class to systematically add classes like `padding-top-1` or `margin-bottom-2` to your your `div` / container elements; or would you prefer to add a default padding/margin directly in your class?

2. Throughout your journey so far, what have you used to customize your design? Have you added `font-weight` or `justify-content`? How about `flex` or `flex-wrap`? Would you find it useful to have a class with different *font-weights* that you could plug directly in your HTML? Your layout doesn't have any font properties; nevertheless I saw your font comments, so perhaps you forgot to save the last version of your file before pushing?

3. Do you have favorite or default background colors that you could add to your framework?

4. Is there anything else you do all the time that could save some coding time by including it right away as a class in your html file? For example, anything with hyperlink, i.e. underline, color, hover, etc (this is just one example)?

Thought:
This is *your framework*, how would it make your life as a developer *easier* or increase the efficiency / speed of your development process, based on *your experience* so far?

Mandatory:
* Add a way to have micro control over spaces in between your containers
* Add font properties to your framework.

**Comment by ngodi** [comment]
many thanks for the review

**Comment by adriaanbd** [comment]
Good job, merge & on to the next project!

**Pull request merged**
